# permissions for end users to view newcas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newca-viewer-role
rules:
- apiGroups:
  - istiocarotation.intel.com
  resources:
  - newcas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - istiocarotation.intel.com
  resources:
  - newcas/status
  verbs:
  - get
