# permissions for end users to edit newcas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newca-editor-role
rules:
- apiGroups:
  - istiocarotation.intel.com
  resources:
  - newcas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - istiocarotation.intel.com
  resources:
  - newcas/status
  verbs:
  - get
